### ISSUE TITLE
Language scope

### ISSUE THREAD

**Issue by martinheidegger** [hypercore-protocol/community#2]
Is this organization language specific (javascript) or are rust, cpp, implementations etc. also encouraged to join here?

**Comment by mafintosh** [comment]
I think it's best to keep this JS only + specs, and eventually even move the JS out to a separate hypercore-js org once we have more stable impls. We should obviously link to all the main impls though from here to have this be the directory of anything hypercore.

**Comment by martinheidegger** [comment]
I don't see the benefit of that strategy.

**Comment by RangerMauve** [comment]
I think it's a good move because it seems the focus of this org is to coordinate development of the JS APIs and the specs under Mathias. The other language implementations are being developed with other groups under different project maintainers so it'd either mean Mathias would need to somehow take responsibility on them, or we'd have a lot of confusion as to who's in charge of what.

**Comment by martinheidegger** [comment]
Sorry for the rough tone: I didn't mean to start a discussion. I was just looking for a statement on this. Which is why I closed the issue.
